Repository corca-ai/adcio.js, pull requests merged in 2023-11, with the labels that each got.

#2 NONE) fix: optional customerId
  src/adcio/adcio.interface.ts
  src/lib/core/core.interface.ts
  src/lib/core/core.ts
Labels: invalid

#3 NONE) build: ready v0.1.0
  package.json
  src/api/controller/v1/.openapi-generator/FILES
  src/api/controller/v1/api.ts
Labels: operations

#7 fix: add on impression
  package.json
  src/adcio/adcio.interface.ts
  src/adcio/adcio.ts
Labels: bug, feature request

#8 NONE) fix: Add expiration timer to SessionStorage
  package.json
  src/lib/storage/session.storage.ts
Labels: bug
