Repository corca-ai/adcio.js, pull requests merged in 2024-02, with the labels that each got.

#29 NONE) feat: add createProductSuggestion for unduplicated suggestion
  src/api/controller/v1/api.ts
  src/lib/placement/placement.interface.ts
  src/lib/placement/placement.ts
Labels: feature request

#30 ADCIO-2517) test: implement react banner demo web
  .github/workflows/ci.yml
  demo/react/.eslintrc.cjs
  demo/react/.gitignore
  demo/react/index.html
  demo/react/package.json
  demo/react/public/mockServiceWorker.js
  demo/react/src/App.tsx
  demo/react/src/component/banner/index.tsx
  demo/react/src/main.tsx
  demo/react/src/pages/Banner.tsx
  demo/react/src/pages/index.tsx
  demo/react/src/styles/banner.css
  demo/react/src/vite-env.d.ts
  demo/react/tsconfig.json
  demo/react/vite.config.ts
  demo/react/yarn.lock
  mock/browser.ts
  mock/constants.ts
  mock/handlers.ts
  mock/node.ts
  mock/suggestion.demo.ts
  mockServiceWorker.js
  package.json
  src/__tests__/mock/suggestion.demo.ts
  src/tests/adcio.spec.ts
  src/tests/setup.ts
  yarn.lock
Labels: test

#33 NONE) fix: add suggestionProducts and update api diff
  src/adcio/adcio.interface.ts
  src/adcio/adcio.ts
  src/api/controller/v1/api.ts
  src/lib/placement/index.ts
Labels: bug
